spring:
  application:
    name: school-service
      
  datasource:
    url: jdbc:mysql://localhost/SCHOOL_SERVICE
    username: 
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    
#server:
 # port: 8000
  
eureka:
  client:
    service-url:
      defaultZone: http://mks-discovery-server-brave-hedgehog.cfapps.io/eureka
