spring:
  application:
    name: school-service
  jpa:
    hibernate:
      ddl-auto: update
      
  datasource:
    url: jdbc:mysql://localhost:3306/SCHOOL_SERVICE
    username: 
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
    
server:
  port: 8000
  
eureka:
  client:
    service-url:
      defaultZone: http://mks-discovery-server-brave-hedgehog.cfapps.io/eureka
