spring:
  application:
    name: school-service
  jpa:
    hibernate:
      ddl-auto: update
      
  datasource:
    url: jdbc:mysql://localhost:3306/SCHOOL_SERVICE
    username: root
    password: root
    
server:
  port: 8000
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
